env:
  es6: true
  browser: true
  node: true
extends: 'eslint:recommended'
plugins:
    - typescript
parser: 'typescript-eslint-parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - single
  semi:
    - error
    - never
